//! Tree-session round-trip tests (#684, ADR-038) — the clean-diff guarantee.
//!
//! Fixture: `tests/fixtures/exploded-basic/`, generated by the pristine
//! pre-change CLI (see plans/684-vfs-tree-primary-model.md Phase 0). It
//! includes decoy files (`README.md`, `.github/workflows/ci.yml`) that no
//! SRS code may touch, and a Type carrying `$schema`/`aiGuidance` extras.

use srs_core::types::record::FieldValue;
use srs_repository::json_store::JsonStore;
use srs_repository::record_store::{
    list_record_summaries, update_record, RecordListFilter, UpdateRecordInput,
};
use srs_repository::validation::validate_repository;
use srs_repository::{export_tree, materialize_tree, open_tree, FileStore, RepositoryStore};
use std::collections::BTreeMap;
use std::path::Path;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/exploded-basic");
const RECORD_1: &str = "0ce8cbdd-5a77-4740-a34a-83b3afa63a3e";
const TYPE_ID: &str = "33333333-3333-4333-8333-333333333331";
const FIELD_TITLE: &str = "22222222-2222-4222-8222-222222222221";
const FIELD_APPROVED: &str = "22222222-2222-4222-8222-222222222222";

/// Load the exploded fixture as a path→bytes map (as a git-tree fetch would).
fn fixture_map() -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, map: &mut BTreeMap<String, Vec<u8>>) {
        for entry in std::fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(root, &path, map);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                map.insert(rel, std::fs::read(&path).unwrap());
            }
        }
    }
    let root = Path::new(FIXTURE);
    let mut map = BTreeMap::new();
    walk(root, root, &mut map);
    assert!(
        map.contains_key("manifest.json"),
        "fixture missing manifest.json — was the fixture committed?"
    );
    map
}

/// Assert `exported` equals `base` except for exactly `expect_changed` (differing
/// or added) keys. Reports precise per-key mismatches on failure.
fn assert_diff_is_exactly(
    base: &BTreeMap<String, Vec<u8>>,
    exported: &BTreeMap<String, Vec<u8>>,
    expect_changed: &[&str],
) {
    let mut changed: Vec<&str> = Vec::new();
    for (key, bytes) in exported {
        match base.get(key) {
            Some(prev) if prev == bytes => {}
            _ => changed.push(key),
        }
    }
    let mut deleted: Vec<&str> = base
        .keys()
        .filter(|k| !exported.contains_key(*k))
        .map(|k| k.as_str())
        .collect();
    changed.sort_unstable();
    deleted.sort_unstable();
    let mut expected: Vec<&str> = expect_changed.to_vec();
    expected.sort_unstable();
    assert_eq!(
        changed, expected,
        "changed/added keys differ from expectation"
    );
    assert!(deleted.is_empty(), "unexpected deletions: {deleted:?}");
}

#[test]
fn open_export_roundtrip_byte_identical() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();
    let exported = export_tree(&store).unwrap();
    // The fixture already contains `.srs/.gitkeep`, so the round-trip must be
    // exactly identical — every byte of every file.
    assert_eq!(
        base, exported,
        "untouched tree must round-trip byte-identically"
    );
}

#[test]
fn export_tree_synthesizes_marker() {
    let mut base = fixture_map();
    base.remove(".srs/.gitkeep");
    let store = open_tree(base.clone()).unwrap();
    let exported = export_tree(&store).unwrap();
    assert_diff_is_exactly(&base, &exported, &[".srs/.gitkeep"]);
    assert_eq!(exported[".srs/.gitkeep"], Vec::<u8>::new());
}

#[test]
fn single_record_edit_single_file_diff() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();
    // Flip `approved` on record 1; title unchanged so the manifest index
    // entry (title/tags) is byte-stable.
    update_record(
        &store,
        RECORD_1,
        UpdateRecordInput {
            field_values: vec![
                FieldValue {
                    field_id: FIELD_TITLE.to_string(),
                    value: serde_json::json!("Adopt the tree model"),
                    entries: None,
                    source: None,
                    edited_at: None,
                },
                FieldValue {
                    field_id: FIELD_APPROVED.to_string(),
                    value: serde_json::json!(false),
                    entries: None,
                    source: None,
                    edited_at: None,
                },
            ],
            group_values: None,
            tags: None,
            type_version: None,
        },
    )
    .unwrap();
    let exported = export_tree(&store).unwrap();
    assert_diff_is_exactly(&base, &exported, &["records/tier-2/decision-0ce8cbdd.json"]);
    let record: serde_json::Value =
        serde_json::from_slice(&exported["records/tier-2/decision-0ce8cbdd.json"]).unwrap();
    let approved = record["fieldValues"]
        .as_array()
        .unwrap()
        .iter()
        .find(|fv| fv["fieldId"] == FIELD_APPROVED)
        .unwrap();
    assert_eq!(approved["value"], serde_json::json!(false));
}

#[test]
fn type_edit_preserves_extra() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();

    // Load fix: extras must be present after load (dropped before #684).
    let mut record_type =
        srs_repository::package_service::get_type_by_id_latest(&store, TYPE_ID).unwrap();
    let rt = match &mut record_type {
        srs_repository::package_service::GetTypeResult::Found(rt) => rt,
        other => panic!("type not found: {other:?}"),
    };
    assert_eq!(
        rt.extra.get("aiGuidance").and_then(|v| v.as_str()),
        Some(
            "A decision made by the group. Title states the decision; \
             approved records whether it was ratified."
        ),
        "aiGuidance must survive load"
    );

    rt.description = "A decision record (edited)".to_string();
    srs_repository::package_service::update_type(&store, rt.clone()).unwrap();

    let exported = export_tree(&store).unwrap();
    assert_diff_is_exactly(&base, &exported, &["package/types/decision-33333333.json"]);
    let written: serde_json::Value =
        serde_json::from_slice(&exported["package/types/decision-33333333.json"]).unwrap();
    assert_eq!(
        written["$schema"], "https://srs.semanticops.com/schema/2.0/type.json",
        "$schema must survive load → edit → save"
    );
    assert!(
        written["aiGuidance"]
            .as_str()
            .unwrap()
            .starts_with("A decision made"),
        "aiGuidance must survive load → edit → save"
    );
    assert_eq!(written["description"], "A decision record (edited)");
}

#[test]
fn decoys_untouched_after_edits() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();
    update_record(
        &store,
        RECORD_1,
        UpdateRecordInput {
            field_values: vec![FieldValue {
                field_id: FIELD_TITLE.to_string(),
                value: serde_json::json!("Retitled decision"),
                entries: None,
                source: None,
                edited_at: None,
            }],
            group_values: None,
            tags: None,
            type_version: None,
        },
    )
    .unwrap();
    let exported = export_tree(&store).unwrap();
    for decoy in ["README.md", ".github/workflows/ci.yml"] {
        assert_eq!(
            base[decoy], exported[decoy],
            "decoy {decoy} must ride through byte-identical"
        );
    }
}

#[test]
fn open_tree_missing_manifest_errors() {
    let mut map = BTreeMap::new();
    map.insert("README.md".to_string(), b"not a repo".to_vec());
    let err = open_tree(map).unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.to_lowercase().contains("manifest"),
        "error should name the missing manifest: {msg}"
    );
}

#[test]
fn export_tree_disk_store_errors() {
    let store = FileStore::new(FIXTURE);
    assert!(store.repository_exists().unwrap());
    let err = export_tree(&store).unwrap_err();
    assert!(
        err.to_string().contains("memory-backed"),
        "disk stores must be rejected: {err}"
    );
}

#[test]
fn materialize_from_srsj_parity() {
    // Build a .srsj envelope from the fixture's SRS files (what a JsonStore
    // session holds), load it as a JsonStore, materialize into a tree, and
    // compare validate/list outputs against the direct tree session.
    let base = fixture_map();
    let mut data = serde_json::Map::new();
    let mut manifest = serde_json::Value::Null;
    for (path, bytes) in &base {
        if path == "manifest.json" {
            manifest = serde_json::from_slice(bytes).unwrap();
            continue;
        }
        if !path.ends_with(".json") || path.starts_with(".github/") {
            continue;
        }
        data.insert(
            path.clone(),
            serde_json::from_slice::<serde_json::Value>(bytes).unwrap(),
        );
    }
    let envelope = serde_json::json!({ "srsj": "1", "manifest": manifest, "data": data });
    let json_store = JsonStore::from_srsj(&envelope.to_string()).unwrap();

    let tree = materialize_tree(&json_store).unwrap();
    let direct = open_tree(base).unwrap();

    let report_tree = validate_repository(&tree).unwrap();
    let report_direct = validate_repository(&direct).unwrap();
    assert_eq!(
        report_tree.diagnostics.len(),
        report_direct.diagnostics.len(),
        "validate parity: tree={:?} direct={:?}",
        report_tree.diagnostics,
        report_direct.diagnostics
    );

    let mut ids_tree: Vec<String> = list_record_summaries(&tree, RecordListFilter::default())
        .unwrap()
        .into_iter()
        .map(|r| r.instance_id)
        .collect();
    let mut ids_direct: Vec<String> = list_record_summaries(&direct, RecordListFilter::default())
        .unwrap()
        .into_iter()
        .map(|r| r.instance_id)
        .collect();
    ids_tree.sort();
    ids_direct.sort();
    assert_eq!(ids_tree, ids_direct, "record inventory parity");
}
