//! Tree-session round-trip tests (#684, ADR-038) — the clean-diff guarantee.
//!
//! Fixture: `tests/fixtures/exploded-basic/`, generated by the pristine
//! pre-change CLI (see plans/684-vfs-tree-primary-model.md Phase 0). It
//! includes decoy files (`README.md`, `.github/workflows/ci.yml`) that no
//! SRS code may touch, and a Type carrying `$schema`/`aiGuidance` extras.

use srs_core::types::record::FieldValues;
use srs_repository::migration_registry_service::{list_migrations, MigrationStatus};
use srs_repository::record_store::{
    list_record_summaries, update_record, RecordListFilter, UpdateRecordInput,
};
use srs_repository::validation::validate_repository;
use srs_repository::{export_tree, materialize_tree, open_tree, FileStore, RepositoryStore};
use std::collections::BTreeMap;
use std::path::Path;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/exploded-basic");
const RECORD_1: &str = "0ce8cbdd-5a77-4740-a34a-83b3afa63a3e";
const TYPE_ID: &str = "33333333-3333-4333-8333-333333333331";

/// Load the exploded fixture as a path→bytes map (as a git-tree fetch would).
fn fixture_map() -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, map: &mut BTreeMap<String, Vec<u8>>) {
        for entry in std::fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(root, &path, map);
            } else {
                let rel = path
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                map.insert(rel, std::fs::read(&path).unwrap());
            }
        }
    }
    let root = Path::new(FIXTURE);
    let mut map = BTreeMap::new();
    walk(root, root, &mut map);
    assert!(
        map.contains_key("manifest.json"),
        "fixture missing manifest.json — was the fixture committed?"
    );
    map
}

/// Assert `exported` equals `base` except for exactly `expect_changed` (differing
/// or added) keys. Reports precise per-key mismatches on failure.
fn assert_diff_is_exactly(
    base: &BTreeMap<String, Vec<u8>>,
    exported: &BTreeMap<String, Vec<u8>>,
    expect_changed: &[&str],
) {
    let mut changed: Vec<&str> = Vec::new();
    for (key, bytes) in exported {
        match base.get(key) {
            Some(prev) if prev == bytes => {}
            _ => changed.push(key),
        }
    }
    let mut deleted: Vec<&str> = base
        .keys()
        .filter(|k| !exported.contains_key(*k))
        .map(|k| k.as_str())
        .collect();
    changed.sort_unstable();
    deleted.sort_unstable();
    let mut expected: Vec<&str> = expect_changed.to_vec();
    expected.sort_unstable();
    assert_eq!(
        changed, expected,
        "changed/added keys differ from expectation"
    );
    assert!(deleted.is_empty(), "unexpected deletions: {deleted:?}");
}

#[test]
fn open_export_roundtrip_byte_identical() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();
    let exported = export_tree(&store).unwrap();
    // The fixture already contains `.srs/.gitkeep`, so the round-trip must be
    // exactly identical — every byte of every file.
    assert_eq!(
        base, exported,
        "untouched tree must round-trip byte-identically"
    );
}

#[test]
fn export_tree_synthesizes_marker() {
    let mut base = fixture_map();
    base.remove(".srs/.gitkeep");
    let store = open_tree(base.clone()).unwrap();
    let exported = export_tree(&store).unwrap();
    assert_diff_is_exactly(&base, &exported, &[".srs/.gitkeep"]);
    assert_eq!(exported[".srs/.gitkeep"], Vec::<u8>::new());
}

#[test]
fn single_record_edit_single_file_diff() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();
    // Flip `approved` on record 1; title unchanged so the manifest index
    // entry (title/tags) is byte-stable.
    update_record(
        &store,
        RECORD_1,
        UpdateRecordInput {
            field_meta: None,
            field_values: {
                let mut fv = FieldValues::new();
                fv.insert("title", serde_json::json!("Adopt the tree model"));
                fv.insert("approved", serde_json::json!(false));
                fv
            },
            tags: None,
            type_version: None,
        },
    )
    .unwrap();
    let exported = export_tree(&store).unwrap();
    assert_diff_is_exactly(&base, &exported, &["records/tier-2/decision-0ce8cbdd.json"]);
    let record: serde_json::Value =
        serde_json::from_slice(&exported["records/tier-2/decision-0ce8cbdd.json"]).unwrap();
    assert_eq!(record["fieldValues"]["approved"], serde_json::json!(false));
}

#[test]
fn type_edit_preserves_extra() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();

    // Load fix: extras must be present after load (dropped before #684).
    let mut record_type =
        srs_repository::package_service::get_type_by_id_latest(&store, TYPE_ID).unwrap();
    let rt = match &mut record_type {
        srs_repository::package_service::GetTypeResult::Found(rt) => rt,
        other => panic!("type not found: {other:?}"),
    };
    assert_eq!(
        rt.extra
            .get("aiGuidance")
            .and_then(|v| v.get("purpose"))
            .and_then(|v| v.as_str()),
        Some(
            "A decision made by the group. Title states the decision; \
             approved records whether it was ratified."
        ),
        "aiGuidance must survive load"
    );

    rt.description = "A decision record (edited)".to_string();
    srs_repository::package_service::update_type(&store, rt.clone()).unwrap();

    let exported = export_tree(&store).unwrap();
    assert_diff_is_exactly(&base, &exported, &["package/types/decision-33333333.json"]);
    let written: serde_json::Value =
        serde_json::from_slice(&exported["package/types/decision-33333333.json"]).unwrap();
    assert_eq!(
        written["$schema"], "https://srs.semanticops.com/schema/2.0/type.json",
        "$schema must survive load → edit → save"
    );
    assert!(
        written["aiGuidance"]["purpose"]
            .as_str()
            .unwrap()
            .starts_with("A decision made"),
        "aiGuidance must survive load → edit → save"
    );
    assert_eq!(written["description"], "A decision record (edited)");
}

#[test]
fn decoys_untouched_after_edits() {
    let base = fixture_map();
    let store = open_tree(base.clone()).unwrap();
    update_record(
        &store,
        RECORD_1,
        UpdateRecordInput {
            field_meta: None,
            field_values: {
                let mut fv = FieldValues::new();
                fv.insert("title", serde_json::json!("Retitled decision"));
                fv
            },
            tags: None,
            type_version: None,
        },
    )
    .unwrap();
    let exported = export_tree(&store).unwrap();
    for decoy in ["README.md", ".github/workflows/ci.yml"] {
        assert_eq!(
            base[decoy], exported[decoy],
            "decoy {decoy} must ride through byte-identical"
        );
    }
}

#[test]
fn open_tree_missing_manifest_errors() {
    let mut map = BTreeMap::new();
    map.insert("README.md".to_string(), b"not a repo".to_vec());
    let err = open_tree(map).unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.to_lowercase().contains("manifest"),
        "error should name the missing manifest: {msg}"
    );
}

#[test]
fn export_tree_disk_store_errors() {
    let store = FileStore::new(FIXTURE);
    assert!(store.repository_exists().unwrap());
    let err = export_tree(&store).unwrap_err();
    assert!(
        err.to_string().contains("memory-backed"),
        "disk stores must be rejected: {err}"
    );
}

#[test]
fn materialize_from_srsj_parity() {
    // Build a .srsj envelope from the fixture's SRS files (what a FileStore
    // session holds), load it as a FileStore, materialize into a tree, and
    // compare validate/list outputs against the direct tree session.
    let base = fixture_map();
    let mut data = serde_json::Map::new();
    let mut manifest = serde_json::Value::Null;
    for (path, bytes) in &base {
        if path == "manifest.json" {
            manifest = serde_json::from_slice(bytes).unwrap();
            continue;
        }
        if !path.ends_with(".json") || path.starts_with(".github/") {
            continue;
        }
        data.insert(
            path.clone(),
            serde_json::from_slice::<serde_json::Value>(bytes).unwrap(),
        );
    }
    let envelope = serde_json::json!({ "srsj": "2", "manifest": manifest, "data": data });
    let json_store = srs_repository::srsj::open_srsj(&envelope.to_string()).unwrap();

    let tree = materialize_tree(&json_store).unwrap();
    let direct = open_tree(base).unwrap();

    let report_tree = validate_repository(&tree).unwrap();
    let report_direct = validate_repository(&direct).unwrap();
    assert_eq!(
        report_tree.diagnostics.len(),
        report_direct.diagnostics.len(),
        "validate parity: tree={:?} direct={:?}",
        report_tree.diagnostics,
        report_direct.diagnostics
    );

    let mut ids_tree: Vec<String> = list_record_summaries(&tree, RecordListFilter::default())
        .unwrap()
        .into_iter()
        .map(|r| r.instance_id)
        .collect();
    let mut ids_direct: Vec<String> = list_record_summaries(&direct, RecordListFilter::default())
        .unwrap()
        .into_iter()
        .map(|r| r.instance_id)
        .collect();
    ids_tree.sort();
    ids_direct.sort();
    assert_eq!(ids_tree, ids_direct, "record inventory parity");
}

/// Rewrite `base` so every instance file sits at a bare full-UUID path
/// (`records/tier-N/<uuid>.json`) instead of the canonical slug-id8 form, mirroring a
/// repository authored before the slug-id8 convention (as srs-web's gallery/sample `.srsj`
/// fixtures are). Returns a `.srsj` envelope string.
fn srsj_with_noncanonical_instance_paths(base: &BTreeMap<String, Vec<u8>>) -> String {
    // RFC-038: membership is the tree — non-canonical placement is expressed
    // by renaming the instance files' data keys to bare full-UUID filenames,
    // not by patching a manifest index (retired).
    let manifest: serde_json::Value = serde_json::from_slice(&base["manifest.json"]).unwrap();
    let mut data = serde_json::Map::new();
    for (path, bytes) in base {
        if path == "manifest.json" || !path.ends_with(".json") || path.starts_with(".github/") {
            continue;
        }
        let value = serde_json::from_slice::<serde_json::Value>(bytes).unwrap();
        let key = if path.starts_with("records/") {
            match value.get("instanceId").and_then(|v| v.as_str()) {
                Some(id) => {
                    let dir = path.rsplit_once('/').map(|(d, _)| d).unwrap_or("records");
                    format!("{dir}/{id}.json")
                }
                None => path.clone(),
            }
        } else {
            path.clone()
        };
        data.insert(key, value);
    }
    serde_json::json!({ "srsj": "2", "manifest": manifest, "data": data }).to_string()
}

#[test]
fn materialize_preserves_noncanonical_paths_and_keeps_repo_upgrade_detectable() {
    // Regression 2 (srs-rust#696): loading a `.srsj` whose instance files sit at NON-canonical
    // paths (bare full-UUID filenames, as srs-web's gallery/sample fixtures use) must preserve
    // those paths through `materialize_tree` rather than re-canonicalizing on load. Otherwise the
    // `repo-upgrade` ("Normalise instance file paths") migration can no longer detect the repo as
    // needing normalization — the build.226 regression where the Needed badge vanished.
    let base = fixture_map();
    let json_store =
        srs_repository::srsj::open_srsj(&srsj_with_noncanonical_instance_paths(&base)).unwrap();

    let tree = materialize_tree(&json_store).unwrap();

    // (a) Real paths preserved — not re-canonicalized to the slug-id8 form on
    // load. The catalog's locators are the placement surface post-RFC-038.
    let cat = srs_repository::store::RepositoryStore::catalog(&tree).unwrap();
    assert!(!cat.instances.is_empty(), "fixture must carry instances");
    for e in &cat.instances {
        let locator = e.locator.as_deref().expect("file-tree locator");
        assert!(
            locator.ends_with(&format!("/{}.json", e.id)),
            "materialize must preserve the non-canonical full-UUID path, got {locator}"
        );
    }

    // (b) repo-upgrade is detectable again (was AlreadyApplied in build.226).
    let migrations = list_migrations(&tree).unwrap();
    let repo_upgrade = migrations
        .iter()
        .find(|m| m.id == "repo-upgrade")
        .expect("repo-upgrade migration must be listed");
    assert_eq!(
        repo_upgrade.status,
        MigrationStatus::Needed,
        "a non-canonical repo must report repo-upgrade as Needed (srs-rust#696 Regression 2)"
    );
}

#[test]
fn materialize_loads_id8_colliding_records() {
    // Regression 1, the browser-load symptom (srs-rust#696): a `.srsj` whose two records share
    // their first 8 hex chars — like gallery.srsj's `…5801`/`…5802` decisions — at unique
    // full-UUID paths must load. The old materialize_tree re-canonicalized both onto one
    // slug-id8 path (`decision-0ce8cbdd.json`) and failed with "canonical path collision".
    let base = fixture_map();
    let manifest: serde_json::Value = serde_json::from_slice(&base["manifest.json"]).unwrap();
    let mut data = serde_json::Map::new();
    for (path, bytes) in &base {
        if path == "manifest.json" || !path.ends_with(".json") || path.starts_with(".github/") {
            continue;
        }
        data.insert(
            path.clone(),
            serde_json::from_slice::<serde_json::Value>(bytes).unwrap(),
        );
    }

    // Clone the fixture's decision (id 0ce8cbdd-…) into an id8-colliding sibling stored at a
    // unique full-UUID path — exactly the shape that crashed on gallery.srsj.
    let colliding_id = "0ce8cbdd-ffff-4fff-bfff-ffffffffffff"; // same id8 "0ce8cbdd"
    let mut clone = data["records/tier-2/decision-0ce8cbdd.json"].clone();
    clone["instanceId"] = serde_json::json!(colliding_id);
    let clone_path = format!("records/tier-2/{colliding_id}.json");
    data.insert(clone_path.clone(), clone);

    let envelope = serde_json::json!({ "srsj": "2", "manifest": manifest, "data": data });
    let json_store = srs_repository::srsj::open_srsj(&envelope.to_string()).unwrap();

    let tree = materialize_tree(&json_store)
        .expect("id8-colliding records must materialize, not collide (srs-rust#696)");

    let ids: Vec<String> = list_record_summaries(&tree, RecordListFilter::default())
        .unwrap()
        .into_iter()
        .map(|r| r.instance_id)
        .collect();
    assert!(
        ids.contains(&RECORD_1.to_string()),
        "original decision present: {ids:?}"
    );
    assert!(
        ids.contains(&colliding_id.to_string()),
        "id8-colliding sibling present: {ids:?}"
    );
}

#[test]
fn materialize_preserves_definition_extras() {
    // Review should-fix (srs-rust#696): materialize_tree is now the mainstream `.srsj` browser
    // load path, running through the faithful `tree_entries` enumeration — package definition
    // extras (`$schema`, `aiGuidance`) must survive it, not just a direct tree open.
    let base = fixture_map();
    let mut data = serde_json::Map::new();
    let mut manifest = serde_json::Value::Null;
    for (path, bytes) in &base {
        if path == "manifest.json" {
            manifest = serde_json::from_slice(bytes).unwrap();
            continue;
        }
        if !path.ends_with(".json") || path.starts_with(".github/") {
            continue;
        }
        data.insert(
            path.clone(),
            serde_json::from_slice::<serde_json::Value>(bytes).unwrap(),
        );
    }
    let envelope = serde_json::json!({ "srsj": "2", "manifest": manifest, "data": data });
    let json_store = srs_repository::srsj::open_srsj(&envelope.to_string()).unwrap();

    let tree = materialize_tree(&json_store).unwrap();
    let exported = export_tree(&tree).unwrap();
    let type_file: serde_json::Value =
        serde_json::from_slice(&exported["package/types/decision-33333333.json"])
            .expect("materialized tree must contain the decision type file");
    assert_eq!(
        type_file["$schema"], "https://srs.semanticops.com/schema/2.0/type.json",
        "$schema must survive materialize_tree from a FileStore"
    );
    assert!(
        type_file["aiGuidance"]["purpose"]
            .as_str()
            .is_some_and(|s| s.starts_with("A decision made")),
        "aiGuidance must survive materialize_tree from a FileStore"
    );
}
