use crate::error::RepositoryError;
use crate::package_types::{validate_package_selector, DefinitionKind, PackageSelector};
use crate::store::RepositoryStore;
use crate::writer::new_instance_id;
use srs_core::types::lifecycle::Lifecycle;
use srs_core::validation::lifecycle::validate_lifecycle;

pub fn list_lifecycles(store: &dyn RepositoryStore) -> Result<Vec<Lifecycle>, RepositoryError> {
    match store.load_package() {
        Ok(package) => Ok(package.lifecycles),
        Err(RepositoryError::Io { .. }) | Err(RepositoryError::PackageLoad { .. }) => Ok(vec![]),
        Err(e) => Err(e),
    }
}

pub fn get_lifecycle_by_id(
    store: &dyn RepositoryStore,
    id: &str,
) -> Result<Option<Lifecycle>, RepositoryError> {
    match store.load_package() {
        Ok(package) => Ok(package.lifecycles.into_iter().find(|lc| lc.id == id)),
        Err(RepositoryError::Io { .. }) | Err(RepositoryError::PackageLoad { .. }) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Result of `create_lifecycle`.
pub struct CreateLifecycleResult {
    pub lifecycle: Lifecycle,
}

/// Create a Lifecycle from a raw JSON value with normalized defaults (issue #511).
///
/// Boilerplate the caller may omit is defaulted before typed deserialization:
/// `createdAt` (now) and `id` (empty string → a new UUID is generated by
/// [`create_lifecycle`]). Explicit values win.
pub fn create_lifecycle_normalized(
    store: &dyn RepositoryStore,
    mut raw: serde_json::Value,
    selector: PackageSelector,
) -> Result<CreateLifecycleResult, RepositoryError> {
    crate::input_normalization::default_created_at(&mut raw, "createdAt");
    crate::input_normalization::default_empty_string(&mut raw, "id");
    let lifecycle = crate::input_normalization::from_value_with_path(raw, "Lifecycle")?;
    create_lifecycle(store, lifecycle, selector)
}

/// Create a new Lifecycle in a specific package boundary.
/// Pass `selector = None` for the primary package; `Some(path)` for a sub-package.
///
/// Writes `<boundary>/lifecycles/{slug}-{id}.json` and adds the path to
/// `<boundary>/package.json` → `lifecycles[]`. If `lifecycle.id` is empty,
/// a new UUID is generated. If `lifecycle.created_at` is empty, the
/// current timestamp is used.
pub fn create_lifecycle(
    store: &dyn RepositoryStore,
    mut lifecycle: Lifecycle,
    selector: PackageSelector,
) -> Result<CreateLifecycleResult, RepositoryError> {
    // Validate the selector form, then that the boundary exists, before touching the filesystem.
    validate_package_selector(&selector)?;
    store.load_package_boundary(&selector)?;

    if lifecycle.id.trim().is_empty() {
        lifecycle.id = new_instance_id();
    }
    if lifecycle.created_at.trim().is_empty() {
        lifecycle.created_at = chrono::Utc::now().to_rfc3339();
    }

    let boundary_path = selector.as_deref().unwrap_or("package");
    let slug = lifecycle
        .name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-");
    let rel_filename = format!("lifecycles/{}-{}.json", slug, &lifecycle.id[..8]);
    let full_path = format!("{boundary_path}/{rel_filename}");

    store.ensure_lifecycles_dir(&format!("{boundary_path}/lifecycles"))?;
    store.save_lifecycle(&full_path, &lifecycle)?;
    store.add_definition_to_boundary(&selector, DefinitionKind::Lifecycle, &rel_filename)?;

    Ok(CreateLifecycleResult { lifecycle })
}

/// Result of `update_lifecycle`.
#[derive(Debug)]
pub struct UpdateLifecycleResult {
    pub lifecycle: Lifecycle,
}

/// Update an existing Lifecycle from a raw JSON value (RFC-028).
///
/// Applies the same `createdAt`/`id` boilerplate defaulting as
/// [`create_lifecycle_normalized`] before typed deserialization, then
/// delegates to [`update_lifecycle`].
pub fn update_lifecycle_normalized(
    store: &dyn RepositoryStore,
    id: &str,
    mut raw: serde_json::Value,
) -> Result<UpdateLifecycleResult, RepositoryError> {
    crate::input_normalization::default_created_at(&mut raw, "createdAt");
    crate::input_normalization::default_empty_string(&mut raw, "id");
    let lifecycle = crate::input_normalization::from_value_with_path(raw, "Lifecycle")?;
    update_lifecycle(store, id, lifecycle)
}

/// Update an existing Lifecycle in place (RFC-028: `srs lifecycle update`).
///
/// Full-replace, not a merge (RFC-028 [R7]): the stored definition after this
/// call is exactly `lifecycle`. The caller owns `version` — it is stored
/// as-is, never auto-incremented (RFC-028 Rationale).
///
/// Validates, in order:
/// - [R3] `lifecycle.id` MUST equal `id`.
/// - [R4] a Lifecycle with `id` MUST already exist in the package.
/// - [R2a] every `LifecycleState` MUST supply `id`, `version` (>= 1), and
///   `namespace` — the RFC-006 VocabularyEntry substrate contract, which the
///   JSON schema does not mark `required` (schema validity alone is not
///   sufficient).
/// - [R5] RFC-006 V9 lifecycle invariants (initial-state uniqueness and
///   activeness, transition state references, final-state/duplicate-id
///   checks — [`validate_lifecycle`]), plus the `initialState` field itself
///   naming the `key` of that one initial state (not checked by
///   `validate_lifecycle`, which only checks the `states[]` side).
///
/// R2a and R5 violations are collected and returned together as
/// [`RepositoryError::LifecycleValidation`] so a caller sees every violation
/// in one round trip, not one-at-a-time.
pub fn update_lifecycle(
    store: &dyn RepositoryStore,
    id: &str,
    lifecycle: Lifecycle,
) -> Result<UpdateLifecycleResult, RepositoryError> {
    // R3
    if lifecycle.id != id {
        return Err(RepositoryError::LifecycleIdMismatch {
            argument_id: id.to_string(),
            body_id: lifecycle.id.clone(),
        });
    }

    // R4
    let (relative_path, _owner) = find_lifecycle_path(store, id)?
        .ok_or_else(|| RepositoryError::LifecycleNotFound { id: id.to_string() })?;

    // R2a: substrate contract on each state (RFC-006 VocabularyEntry).
    let mut violations: Vec<String> = Vec::new();
    for state in &lifecycle.states {
        if state.id.as_deref().unwrap_or("").trim().is_empty() {
            violations.push(format!(
                "state '{}' is missing required substrate field 'id'",
                state.key
            ));
        }
        match state.version {
            Some(v) if v >= 1 => {}
            _ => violations.push(format!(
                "state '{}' is missing required substrate field 'version' (integer >= 1)",
                state.key
            )),
        }
        if state.namespace.as_deref().unwrap_or("").trim().is_empty() {
            violations.push(format!(
                "state '{}' is missing required substrate field 'namespace'",
                state.key
            ));
        }
    }

    // R5: initialState must name the key of the (exactly one) isInitial state.
    // validate_lifecycle checks the states[] side (exactly one isInitial,
    // effectively active); this checks the initialState field agrees with it.
    let initial_by_flag = lifecycle.states.iter().find(|s| s.is_initial == Some(true));
    match initial_by_flag {
        Some(s) if s.key == lifecycle.initial_state => {}
        Some(s) => violations.push(format!(
            "initialState '{}' does not match the isInitial state's key '{}'",
            lifecycle.initial_state, s.key
        )),
        None => {
            // validate_lifecycle already reports V9NoInitialState/V9MultipleInitialStates
            // for the states[] side; nothing to add here beyond that.
        }
    }

    // R5: remaining RFC-006 V9 invariants.
    for diag in validate_lifecycle(&lifecycle) {
        violations.push(diag.message);
    }

    if !violations.is_empty() {
        return Err(RepositoryError::LifecycleValidation { violations });
    }

    store.update_lifecycle_file(&relative_path, &lifecycle)?;
    Ok(UpdateLifecycleResult { lifecycle })
}

/// Find the repo-root-relative path and owner for a standalone Lifecycle by
/// its ID. `None` when the Lifecycle is not owned by this repository (e.g.
/// embedded core package).
///
/// `PackageBoundary` only carries `field_paths`/`type_paths`/`blueprint_paths`/
/// `protocol_paths` — Lifecycle (like View, Composition, RelationType,
/// Vocabulary) is resolved by scanning the owner's `package.json` `lifecycles`
/// array directly (mirrors `view_service::find_view_path`/`find_composition_path`),
/// not `PackageBoundary.lifecycle_paths`, which `MemoryStore` never populates.
pub(crate) fn find_lifecycle_path(
    store: &dyn RepositoryStore,
    id: &str,
) -> Result<Option<(String, PackageSelector)>, RepositoryError> {
    let owner = match store.resolve_definition_owner(id, DefinitionKind::Lifecycle) {
        Ok(sel) => sel,
        Err(RepositoryError::DefinitionNotFound { .. }) => return Ok(None),
        Err(e) => return Err(e),
    };
    let prefix = owner.as_deref().unwrap_or("package");
    let pkg_json = store.load_instance_json(&format!("{prefix}/package.json"))?;
    let paths = pkg_json["lifecycles"]
        .as_array()
        .cloned()
        .unwrap_or_default();
    for entry in &paths {
        if let Some(rel) = entry.as_str() {
            let full = format!("{prefix}/{rel}");
            if let Ok(val) = store.load_instance_json(&full) {
                if val["id"].as_str() == Some(id) {
                    return Ok(Some((full, owner)));
                }
            }
        }
    }
    Ok(None)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::memory::MemoryStore;
    use srs_core::types::lifecycle::{LifecycleState, LifecycleTransition};

    fn make_lifecycle() -> Lifecycle {
        Lifecycle {
            schema: None,
            tags: None,
            id: "lc-test-id".to_string(),
            version: 1,
            namespace: "com.test".to_string(),
            name: "test-lifecycle".to_string(),
            states: vec![
                LifecycleState {
                    id: Some("s1".to_string()),
                    version: None,
                    namespace: None,
                    key: "draft".to_string(),
                    label: None,
                    description: None,
                    aliases: None,
                    is_initial: Some(true),
                    is_final: None,
                    status: None,
                    requires_relation: None,
                    meta: None,
                },
                LifecycleState {
                    id: Some("s2".to_string()),
                    version: None,
                    namespace: None,
                    key: "active".to_string(),
                    label: None,
                    description: None,
                    aliases: None,
                    is_initial: None,
                    is_final: Some(true),
                    status: None,
                    requires_relation: None,
                    meta: None,
                },
            ],
            transitions: vec![LifecycleTransition {
                id: Some("t1".to_string()),
                name: "publish".to_string(),
                from: "draft".to_string(),
                to: "active".to_string(),
                description: None,
                meta: None,
            }],
            initial_state: "draft".to_string(),
            extends_lifecycle_id: None,
            extends_lifecycle_version: None,
            description: None,
            created_at: "2026-01-01T00:00:00Z".to_string(),
        }
    }

    #[test]
    fn list_lifecycles_empty_when_no_package() {
        let store = MemoryStore::default();
        let result = list_lifecycles(&store).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn get_lifecycle_by_id_returns_none_when_missing() {
        let store = MemoryStore::default();
        let result = get_lifecycle_by_id(&store, "00000000-0000-0000-0000-000000000000").unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn create_lifecycle_assigns_id_and_is_retrievable() {
        let store = MemoryStore::default();
        let lc = make_lifecycle();
        let result = create_lifecycle(&store, lc, None).unwrap();
        assert_eq!(result.lifecycle.name, "test-lifecycle");
        assert!(!result.lifecycle.id.is_empty());

        let lifecycles = list_lifecycles(&store).unwrap();
        assert_eq!(lifecycles.len(), 1);
        assert_eq!(lifecycles[0].name, "test-lifecycle");

        let found = get_lifecycle_by_id(&store, &result.lifecycle.id).unwrap();
        assert!(found.is_some());
    }

    #[test]
    fn create_lifecycle_in_memory_sub_package_registers_in_boundary() {
        let store = MemoryStore::default();
        let selector = Some("packages/governance".to_string());
        store.register_package_boundary(&selector).unwrap();

        let result = create_lifecycle(&store, make_lifecycle(), selector).unwrap();

        let data = store.all_data();
        assert!(
            data.keys()
                .any(|k| k.starts_with("packages/governance/lifecycles/")),
            "lifecycle file should be written under the boundary directory"
        );
        let pkg_json = data.get("packages/governance/package.json").unwrap();
        assert!(
            pkg_json["lifecycles"]
                .as_array()
                .unwrap()
                .iter()
                .any(|v| v.as_str().unwrap_or("").starts_with("lifecycles/")),
            "lifecycle should be registered in the boundary's package.json"
        );
        // Visible through the merged package view.
        let lifecycles = list_lifecycles(&store).unwrap();
        assert!(lifecycles.iter().any(|lc| lc.id == result.lifecycle.id));
    }

    #[test]
    fn create_lifecycle_in_file_sub_package_registers_and_lists() {
        // Cross-store coverage for the same behavior verified on MemoryStore above.
        use crate::package_service::{create_package, CreatePackageInput};
        use crate::store::FileStore;

        let temp = tempfile::TempDir::new().unwrap();
        std::fs::create_dir_all(temp.path().join(".srs")).unwrap();
        std::fs::write(
            temp.path().join("manifest.json"),
            r#"{"dataModelRevision":2}"#,
        )
        .unwrap();
        std::fs::create_dir_all(temp.path().join("package")).unwrap();
        std::fs::write(
            temp.path().join("package/package.json"),
            serde_json::json!({
                "id": "pkg",
                "namespace": "com.test",
                "name": "test",
                "version": "1.0.0",
                "fields": [],
                "types": []
            })
            .to_string(),
        )
        .unwrap();
        let store = FileStore::new(temp.path());
        create_package(
            &store,
            CreatePackageInput {
                id: "gov-pkg".to_string(),
                namespace: "com.gov".to_string(),
                name: "governance".to_string(),
                version: "1.0.0".to_string(),
                boundary_path: Some("packages/governance".to_string()),
            },
        )
        .unwrap();

        let created = create_lifecycle(
            &store,
            make_lifecycle(),
            Some("packages/governance".to_string()),
        )
        .unwrap();

        // File written into the boundary's directory.
        let lc_dir = temp.path().join("packages/governance/lifecycles");
        assert!(lc_dir.is_dir(), "lifecycles dir should exist in boundary");

        // Registered in the boundary's package.json lifecycles array.
        let pkg_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(temp.path().join("packages/governance/package.json")).unwrap(),
        )
        .unwrap();
        assert!(
            pkg_json["lifecycles"]
                .as_array()
                .unwrap()
                .iter()
                .any(|v| v.as_str().unwrap_or("").starts_with("lifecycles/")),
            "lifecycle should be registered in the boundary's package.json"
        );

        // Merged into the package view: list sees the sub-package lifecycle.
        let lifecycles = list_lifecycles(&store).unwrap();
        assert!(
            lifecycles.iter().any(|lc| lc.id == created.lifecycle.id),
            "sub-package lifecycle should appear in list_lifecycles"
        );
        let found = get_lifecycle_by_id(&store, &created.lifecycle.id).unwrap();
        assert!(found.is_some());
    }

    #[test]
    fn lifecycle_roundtrips_json() {
        let lc = make_lifecycle();
        let json = serde_json::to_string(&lc).unwrap();
        let parsed: Lifecycle = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.states.len(), 2);
        assert_eq!(parsed.states[0].key, "draft");
        assert_eq!(parsed.transitions[0].name, "publish");
        assert_eq!(parsed.initial_state, "draft");
    }

    // --- update_lifecycle (RFC-028, srs-rust#919) ---

    /// A lifecycle whose states carry the full RFC-006 VocabularyEntry
    /// substrate ([R2a]: `id`, `version`, `namespace`) — what a real
    /// `lifecycle update` caller sends, unlike `make_lifecycle()`'s
    /// intentionally-sparse states (which exist to test `create_lifecycle`'s
    /// own boilerplate, not R2a).
    fn make_substrate_lifecycle(id: &str) -> Lifecycle {
        let mut lc = make_lifecycle();
        lc.id = id.to_string();
        for (i, state) in lc.states.iter_mut().enumerate() {
            state.id = Some(format!("state-{i}"));
            state.version = Some(1);
            state.namespace = Some("com.test".to_string());
        }
        lc
    }

    #[test]
    fn update_lifecycle_replaces_definition_in_place() {
        let store = MemoryStore::default();
        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();
        let id = created.lifecycle.id.clone();

        let mut updated = created.lifecycle.clone();
        updated.version = 2;
        updated.description = Some("added an abandoned state".to_string());

        let result = update_lifecycle(&store, &id, updated).unwrap();
        assert_eq!(result.lifecycle.version, 2);
        assert_eq!(
            result.lifecycle.description.as_deref(),
            Some("added an abandoned state")
        );

        // Full-replace is visible through get/list too — not just the return value.
        let fetched = get_lifecycle_by_id(&store, &id).unwrap().unwrap();
        assert_eq!(fetched.version, 2);
        let listed = list_lifecycles(&store).unwrap();
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0].version, 2);
    }

    #[test]
    fn update_lifecycle_rejects_id_mismatch() {
        let store = MemoryStore::default();
        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();

        let mut body = created.lifecycle.clone();
        body.id = "a-different-id".to_string();

        let err = update_lifecycle(&store, &created.lifecycle.id, body).unwrap_err();
        assert!(matches!(err, RepositoryError::LifecycleIdMismatch { .. }));
    }

    #[test]
    fn update_lifecycle_rejects_unknown_id() {
        let store = MemoryStore::default();
        let body = make_substrate_lifecycle("00000000-0000-0000-0000-000000000000");

        let err =
            update_lifecycle(&store, "00000000-0000-0000-0000-000000000000", body).unwrap_err();
        assert!(matches!(err, RepositoryError::LifecycleNotFound { .. }));
    }

    #[test]
    fn update_lifecycle_rejects_state_missing_substrate_fields() {
        let store = MemoryStore::default();
        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();

        let mut body = created.lifecycle.clone();
        body.states[0].version = None; // strip R2a substrate field

        let err = update_lifecycle(&store, &body.id.clone(), body).unwrap_err();
        match err {
            RepositoryError::LifecycleValidation { violations } => {
                assert!(
                    violations.iter().any(|v| v.contains("version")),
                    "expected a 'version' substrate violation, got: {violations:?}"
                );
            }
            other => panic!("expected LifecycleValidation, got: {other:?}"),
        }
    }

    #[test]
    fn update_lifecycle_rejects_initial_state_mismatch() {
        let store = MemoryStore::default();
        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();

        let mut body = created.lifecycle.clone();
        body.initial_state = "active".to_string(); // "draft" is still the isInitial state

        let err = update_lifecycle(&store, &body.id.clone(), body).unwrap_err();
        match err {
            RepositoryError::LifecycleValidation { violations } => {
                assert!(
                    violations.iter().any(|v| v.contains("initialState")),
                    "expected an initialState mismatch violation, got: {violations:?}"
                );
            }
            other => panic!("expected LifecycleValidation, got: {other:?}"),
        }
    }

    #[test]
    fn update_lifecycle_rejects_v9_violations() {
        let store = MemoryStore::default();
        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();

        let mut body = created.lifecycle.clone();
        // Transition references an unknown state key (V9c).
        body.transitions[0].to = "nonexistent".to_string();

        let err = update_lifecycle(&store, &body.id.clone(), body).unwrap_err();
        match err {
            RepositoryError::LifecycleValidation { violations } => {
                assert!(
                    violations.iter().any(|v| v.contains("nonexistent")),
                    "expected a V9 unknown-transition-state violation, got: {violations:?}"
                );
            }
            other => panic!("expected LifecycleValidation, got: {other:?}"),
        }
    }

    /// Cross-store coverage (storage-boundary rule): `find_lifecycle_path`
    /// resolves via a package.json array scan, not `PackageBoundary
    /// .lifecycle_paths` — prove it also works against `FileStore`, not just
    /// the in-memory fast path.
    #[test]
    fn update_lifecycle_in_file_store_replaces_definition_on_disk() {
        use crate::store::FileStore;

        let temp = tempfile::TempDir::new().unwrap();
        std::fs::create_dir_all(temp.path().join(".srs")).unwrap();
        std::fs::write(
            temp.path().join("manifest.json"),
            r#"{"dataModelRevision":2}"#,
        )
        .unwrap();
        std::fs::create_dir_all(temp.path().join("package")).unwrap();
        std::fs::write(
            temp.path().join("package/package.json"),
            serde_json::json!({
                "id": "pkg",
                "namespace": "com.test",
                "name": "test",
                "version": "1.0.0",
                "fields": [],
                "types": []
            })
            .to_string(),
        )
        .unwrap();
        let store = FileStore::new(temp.path());

        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();
        let id = created.lifecycle.id.clone();

        let mut updated = created.lifecycle.clone();
        updated.version = 2;

        let result = update_lifecycle(&store, &id, updated).unwrap();
        assert_eq!(result.lifecycle.version, 2);

        let fetched = get_lifecycle_by_id(&store, &id).unwrap().unwrap();
        assert_eq!(
            fetched.version, 2,
            "the file on disk must reflect the update"
        );
    }

    #[test]
    fn update_lifecycle_normalized_defaults_id_and_created_at_then_still_requires_match() {
        let store = MemoryStore::default();
        let created = create_lifecycle(&store, make_substrate_lifecycle(""), None).unwrap();
        let id = created.lifecycle.id.clone();

        let mut raw = serde_json::to_value(&created.lifecycle).unwrap();
        raw["version"] = serde_json::json!(2);

        let result = update_lifecycle_normalized(&store, &id, raw).unwrap();
        assert_eq!(result.lifecycle.version, 2);
    }
}
