use crate::error::RepositoryError;
use crate::package_types::{validate_package_selector, DefinitionKind, PackageSelector};
use crate::store::RepositoryStore;
use crate::writer::new_instance_id;
use srs_core::types::lifecycle::Lifecycle;

pub fn list_lifecycles(store: &dyn RepositoryStore) -> Result<Vec<Lifecycle>, RepositoryError> {
    match store.load_package() {
        Ok(package) => Ok(package.lifecycles),
        Err(RepositoryError::Io { .. }) | Err(RepositoryError::PackageLoad { .. }) => Ok(vec![]),
        Err(e) => Err(e),
    }
}

pub fn get_lifecycle_by_id(
    store: &dyn RepositoryStore,
    id: &str,
) -> Result<Option<Lifecycle>, RepositoryError> {
    match store.load_package() {
        Ok(package) => Ok(package.lifecycles.into_iter().find(|lc| lc.id == id)),
        Err(RepositoryError::Io { .. }) | Err(RepositoryError::PackageLoad { .. }) => Ok(None),
        Err(e) => Err(e),
    }
}

/// Result of `create_lifecycle`.
pub struct CreateLifecycleResult {
    pub lifecycle: Lifecycle,
}

/// Create a Lifecycle from a raw JSON value with normalized defaults (issue #511).
///
/// Boilerplate the caller may omit is defaulted before typed deserialization:
/// `createdAt` (now) and `id` (empty string → a new UUID is generated by
/// [`create_lifecycle`]). Explicit values win.
pub fn create_lifecycle_normalized(
    store: &dyn RepositoryStore,
    mut raw: serde_json::Value,
    selector: PackageSelector,
) -> Result<CreateLifecycleResult, RepositoryError> {
    crate::input_normalization::default_created_at(&mut raw, "createdAt");
    crate::input_normalization::default_empty_string(&mut raw, "id");
    let lifecycle = crate::input_normalization::from_value_with_path(raw, "Lifecycle")?;
    create_lifecycle(store, lifecycle, selector)
}

/// Create a new Lifecycle in a specific package boundary.
/// Pass `selector = None` for the primary package; `Some(path)` for a sub-package.
///
/// Writes `<boundary>/lifecycles/{slug}-{id}.json` and adds the path to
/// `<boundary>/package.json` → `lifecycles[]`. If `lifecycle.id` is empty,
/// a new UUID is generated. If `lifecycle.created_at` is empty, the
/// current timestamp is used.
pub fn create_lifecycle(
    store: &dyn RepositoryStore,
    mut lifecycle: Lifecycle,
    selector: PackageSelector,
) -> Result<CreateLifecycleResult, RepositoryError> {
    // Validate the selector form, then that the boundary exists, before touching the filesystem.
    validate_package_selector(&selector)?;
    store.load_package_boundary(&selector)?;

    if lifecycle.id.trim().is_empty() {
        lifecycle.id = new_instance_id();
    }
    if lifecycle.created_at.trim().is_empty() {
        lifecycle.created_at = chrono::Utc::now().to_rfc3339();
    }

    let boundary_path = selector.as_deref().unwrap_or("package");
    let slug = lifecycle
        .name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-");
    let rel_filename = format!("lifecycles/{}-{}.json", slug, &lifecycle.id[..8]);
    let full_path = format!("{boundary_path}/{rel_filename}");

    store.ensure_lifecycles_dir(&format!("{boundary_path}/lifecycles"))?;
    store.save_lifecycle(&full_path, &lifecycle)?;
    store.add_definition_to_boundary(&selector, DefinitionKind::Lifecycle, &rel_filename)?;

    Ok(CreateLifecycleResult { lifecycle })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::memory::MemoryStore;
    use srs_core::types::lifecycle::{LifecycleState, LifecycleTransition};

    fn make_lifecycle() -> Lifecycle {
        Lifecycle {
            id: "lc-test-id".to_string(),
            version: 1,
            namespace: "com.test".to_string(),
            name: "test-lifecycle".to_string(),
            states: vec![
                LifecycleState {
                    id: Some("s1".to_string()),
                    version: None,
                    namespace: None,
                    key: "draft".to_string(),
                    label: None,
                    description: None,
                    aliases: None,
                    is_initial: Some(true),
                    is_final: None,
                    status: None,
                    requires_relation: None,
                    properties: None,
                },
                LifecycleState {
                    id: Some("s2".to_string()),
                    version: None,
                    namespace: None,
                    key: "active".to_string(),
                    label: None,
                    description: None,
                    aliases: None,
                    is_initial: None,
                    is_final: Some(true),
                    status: None,
                    requires_relation: None,
                    properties: None,
                },
            ],
            transitions: vec![LifecycleTransition {
                id: Some("t1".to_string()),
                name: "publish".to_string(),
                from: "draft".to_string(),
                to: "active".to_string(),
                description: None,
                properties: None,
            }],
            initial_state: "draft".to_string(),
            extends_lifecycle_id: None,
            extends_lifecycle_version: None,
            description: None,
            created_at: "2026-01-01T00:00:00Z".to_string(),
            extra: std::collections::BTreeMap::new(),
        }
    }

    #[test]
    fn list_lifecycles_empty_when_no_package() {
        let store = MemoryStore::default();
        let result = list_lifecycles(&store).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn get_lifecycle_by_id_returns_none_when_missing() {
        let store = MemoryStore::default();
        let result = get_lifecycle_by_id(&store, "00000000-0000-0000-0000-000000000000").unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn create_lifecycle_assigns_id_and_is_retrievable() {
        let store = MemoryStore::default();
        let lc = make_lifecycle();
        let result = create_lifecycle(&store, lc, None).unwrap();
        assert_eq!(result.lifecycle.name, "test-lifecycle");
        assert!(!result.lifecycle.id.is_empty());

        let lifecycles = list_lifecycles(&store).unwrap();
        assert_eq!(lifecycles.len(), 1);
        assert_eq!(lifecycles[0].name, "test-lifecycle");

        let found = get_lifecycle_by_id(&store, &result.lifecycle.id).unwrap();
        assert!(found.is_some());
    }

    #[test]
    fn create_lifecycle_in_memory_sub_package_registers_in_boundary() {
        let store = MemoryStore::default();
        let selector = Some("packages/governance".to_string());
        store.register_package_boundary(&selector).unwrap();

        let result = create_lifecycle(&store, make_lifecycle(), selector).unwrap();

        let data = store.all_data();
        assert!(
            data.keys()
                .any(|k| k.starts_with("packages/governance/lifecycles/")),
            "lifecycle file should be written under the boundary directory"
        );
        let pkg_json = data.get("packages/governance/package.json").unwrap();
        assert!(
            pkg_json["lifecycles"]
                .as_array()
                .unwrap()
                .iter()
                .any(|v| v.as_str().unwrap_or("").starts_with("lifecycles/")),
            "lifecycle should be registered in the boundary's package.json"
        );
        // Visible through the merged package view.
        let lifecycles = list_lifecycles(&store).unwrap();
        assert!(lifecycles.iter().any(|lc| lc.id == result.lifecycle.id));
    }

    #[test]
    fn create_lifecycle_in_file_sub_package_registers_and_lists() {
        // Cross-store coverage for the same behavior verified on MemoryStore above.
        use crate::package_service::{create_package, CreatePackageInput};
        use crate::store::FileStore;

        let temp = tempfile::TempDir::new().unwrap();
        std::fs::create_dir_all(temp.path().join(".srs")).unwrap();
        std::fs::write(
            temp.path().join("manifest.json"),
            r#"{"dataModelRevision":2}"#,
        )
        .unwrap();
        std::fs::create_dir_all(temp.path().join("package")).unwrap();
        std::fs::write(
            temp.path().join("package/package.json"),
            serde_json::json!({
                "id": "pkg",
                "namespace": "com.test",
                "name": "test",
                "version": "1.0.0",
                "fields": [],
                "types": []
            })
            .to_string(),
        )
        .unwrap();
        let store = FileStore::new(temp.path());
        create_package(
            &store,
            CreatePackageInput {
                id: "gov-pkg".to_string(),
                namespace: "com.gov".to_string(),
                name: "governance".to_string(),
                version: "1.0.0".to_string(),
                boundary_path: Some("packages/governance".to_string()),
            },
        )
        .unwrap();

        let created = create_lifecycle(
            &store,
            make_lifecycle(),
            Some("packages/governance".to_string()),
        )
        .unwrap();

        // File written into the boundary's directory.
        let lc_dir = temp.path().join("packages/governance/lifecycles");
        assert!(lc_dir.is_dir(), "lifecycles dir should exist in boundary");

        // Registered in the boundary's package.json lifecycles array.
        let pkg_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(temp.path().join("packages/governance/package.json")).unwrap(),
        )
        .unwrap();
        assert!(
            pkg_json["lifecycles"]
                .as_array()
                .unwrap()
                .iter()
                .any(|v| v.as_str().unwrap_or("").starts_with("lifecycles/")),
            "lifecycle should be registered in the boundary's package.json"
        );

        // Merged into the package view: list sees the sub-package lifecycle.
        let lifecycles = list_lifecycles(&store).unwrap();
        assert!(
            lifecycles.iter().any(|lc| lc.id == created.lifecycle.id),
            "sub-package lifecycle should appear in list_lifecycles"
        );
        let found = get_lifecycle_by_id(&store, &created.lifecycle.id).unwrap();
        assert!(found.is_some());
    }

    #[test]
    fn lifecycle_roundtrips_json() {
        let lc = make_lifecycle();
        let json = serde_json::to_string(&lc).unwrap();
        let parsed: Lifecycle = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.states.len(), 2);
        assert_eq!(parsed.states[0].key, "draft");
        assert_eq!(parsed.transitions[0].name, "publish");
        assert_eq!(parsed.initial_state, "draft");
    }
}
